## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Trent Vine - Reigning Record's pop artist"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
googleAnalytics = "G-MV8QM3NPV3"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Kinda like if Post Malone and Justin Bieber had a love baby that was raised by J-Pop. Brace yourself for staggering vocals, fluent Japanese flow, and mainstream songs that will take over your playlists."
  logo = "images/candid-square.jpg"
  favicon = true

[Params.social]
  twitter = "https://twitter.com/trent_vine"
  instagram = "https://www.instagram.com/trentvine/"
  linkedin = "https://au.linkedin.com/in/trent-vine-91720b130"
  facebook = "https://www.facebook.com/trentvinemusic/"

## Custom added
customSCSS = ["scss/custom.scss"]
